'use strict';

/* Controllers */
angular.module('bpEuler.controllers', ['primeNumber']).
  controller('bpPages', ['$scope', function($scope) {
    var totalPages = 5;
    $scope.pages = [];
    for (var pageNumber=1; pageNumber <= totalPages; pageNumber++) {
      $scope.pages.push(
        {  
          'href' : 'problem' + pageNumber,
          'pageName' : 'Euler Problem ' + pageNumber 
        }
      );
    }
  }])
  .controller('bpProblem1', ['$scope', function($scope) {
    $scope.calculateAnswer = function () {
      var sumNumber=0;
      var counter = 0;
      for (var naturalNumber=1; naturalNumber < $scope.inputNumber; naturalNumber++) {
        counter++;
        sumNumber += (naturalNumber % 3 == 0 || naturalNumber % 5 == 0 ? naturalNumber : 0);
      }
      $scope.answer = sumNumber;
      $scope.counter = counter;
    }

    $scope.problem = "1";
    $scope.explanation = ["If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23."];
    $scope.challenge = "Find the sum of all the multiples of 3 or 5 below 1000.";
    $scope.inputNumber = 10;
    $scope.calculateAnswer();
    $scope.expectedAnswer = 233168;
  }])
  .controller('bpProblem2', ['$scope', function($scope) {

    $scope.calculateAnswer = function () {

      var term = 0;
      var sumOfEvens = 0;
      var nTerm = 0;
      var nTermPlusnTerm = 1;
      var newArray = []; 
      var allArray = [];
      var counter = 0;

      term = nTerm + nTermPlusnTerm;
      while (term < $scope.inputNumber) {
        counter++;
        if (term % 2 == 0) {
          sumOfEvens += term;
          newArray.push(term);
        }
        allArray.push(term);
        nTerm = nTermPlusnTerm;
        nTermPlusnTerm = term;
        term = nTerm + nTermPlusnTerm;
      }

      $scope.answer = sumOfEvens
      $scope.newArray = newArray;
      $scope.allArray = allArray;
      $scope.counter = counter;
    }

    $scope.problem = "2";
    $scope.explanation = [
      "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:",
      "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."
    ];
    $scope.challenge = "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
    $scope.inputNumber = 10;
    $scope.calculateAnswer();
    $scope.expectedAnswer = 4613732;
  }])
  .controller('bpProblem3', ['$scope', 'primeNumber', function($scope, primeNumber) {
    $scope._findBiggestPrimeFactor = function() {
      var localSortedKnownFactors = $scope._knownFactors.sort(function(a,b){return a-b});
      return localSortedKnownFactors[localSortedKnownFactors.length-1];
    }

    $scope.calculateAnswer = function () {
      $scope._knownFactors = [];
      var counter = 0;
      var originalNumber = $scope.inputNumber, startingNumber = $scope.inputNumber; 
      var maxSquareRoot = Math.floor(Math.sqrt(startingNumber));
      var quotient = 1;
      var nextPrimeFactor = 2;
      var continueFactoring = true;

      if ($scope.inputNumber == 1) {
        counter++;
        $scope._knownFactors.push(1);
        continueFactoring = false;
      }

      while (continueFactoring) {
        var continueDivision = true;
        while (continueDivision) {
          counter++;
          if (startingNumber % nextPrimeFactor == 0) {
            startingNumber = startingNumber / nextPrimeFactor;
            $scope._knownFactors.push(nextPrimeFactor);
            quotient *= nextPrimeFactor;
            if (quotient >= originalNumber) {
              continueFactoring = false;
              break;
            }
          } else {
            continueDivision = false;
          }
        }
        nextPrimeFactor += (nextPrimeFactor <= 2 ? 1 : 2);
        var primeNumberContinue = true;
        while (primeNumberContinue && nextPrimeFactor < maxSquareRoot) {
          counter++;
          if (primeNumber.isPrimeNumber(nextPrimeFactor) ) {
            primeNumberContinue = false;
          } else {
            nextPrimeFactor += 2;
          }
        } 
      }
      $scope.answer = $scope._findBiggestPrimeFactor();
      $scope.counter = counter;
    }

    $scope.problem = "3";
    $scope.explanation = [
      "The prime factors of 13195 are 5, 7, 13 and 29."
    ];
    $scope.challenge = "What is the largest prime factor of the number 600851475143?";
    $scope.inputNumber = 13195;
    $scope.calculateAnswer();
    $scope.expectedAnswer = 6857;
  }])
  .controller('bpProblem4', ['$scope', function($scope) {

    $scope.calculateAnswer = function () {
      var counter = 0;
      var biggestPalindrome = 0, firstNumber = 0, secondNumber = 0;
      var quotient = 1;
      for (var outerNumber=$scope.inputNumber; outerNumber>0; outerNumber--) {
        for (var innerNumber=$scope.inputNumber; innerNumber>0; innerNumber--) {
          counter++;
          quotient = outerNumber * innerNumber;
          var reversedQuotient = String(quotient).split("").reverse().join("");
          if (quotient == reversedQuotient && quotient >= biggestPalindrome) {
            biggestPalindrome = quotient;
            firstNumber = outerNumber;
            secondNumber = innerNumber;
            if (quotient < biggestPalindrome) {
              break;
            }
          }
        }
      }
      $scope.answer = biggestPalindrome;
      $scope.counter = counter;
      $scope.outerNumber = firstNumber;
      $scope.innerNumber = secondNumber;
    }

    $scope.problem = "4";
    $scope.explanation = [
      "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99."
    ];
    $scope.challenge = "Find the largest palindrome made from the product of two 3-digit numbers.";
    $scope.inputNumber = 99;
    $scope.calculateAnswer();
    $scope.expectedAnswer = 906609;
  }])
  .controller('bpProblem5', ['$scope', 'primeNumber', function($scope, primeNumber) {
    $scope.calculateAnswer = function () {
      var counter = 0;
      var quotient = 1;
      for (var startingNumber=2; startingNumber <= $scope.inputNumber; startingNumber++) {
        counter++;
        if (primeNumber.isPrimeNumber(startingNumber) ) {
          var powerNumber = 1;
          while (Math.pow(startingNumber, powerNumber) < $scope.inputNumber) {
            counter++;
            quotient *= startingNumber;
            powerNumber += 1;
          }
        }
      }
      $scope.answer = quotient;
      $scope.counter = counter;
    }

    $scope.problem = "5";
    $scope.explanation = [
      "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder."
    ];
    $scope.challenge = "What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?";
    $scope.inputNumber = 10;
    $scope.calculateAnswer();
    $scope.expectedAnswer = 232792560;

  }])
  .controller('bpProblemBlank', ['$scope', function($scope) {
    $scope.calculateAnswer = function () {
      var counter = 0;
      $scope.answer = $scope.inputNumber * 2;
      $scope.counter = counter;
    }

    $scope.problem = "";
    $scope.explanation = [
    ];
    $scope.challenge = "";
    $scope.inputNumber = 10;
    $scope.calculateAnswer();
    $scope.expectedAnswer = undefined;

  }])
  ;
